docker-compose.yml

ci: reduce image size by alpine

---

go.mod
go.sum
pkg/evpn/evpn.go

create: use {resource}_id field if provided by user

---

pkg/evpn/evpn.go

AIP-122: use resourcename.Validate and fieldbehavior.ValidateRequiredFields

---

README.md
pkg/evpn/evpn.go

- [subnet]: add Get function
- [interface]: add Get function

add Get function for interface and subnet

---

pkg/evpn/evpn.go

Initial impl for Update* functions

---

go.mod
go.sum
pkg/evpn/evpn.go

Remove tenus. Use netlink

---

docker-compose.yml

ci: remove static bridge config and use grpc

---

README.md
docker-compose.yml
pkg/evpn/evpn.go
pkg/evpn/tunnel_vxlan.go
pkg/evpn/tunnel_vxlan_test.go

Need for vxlan
Plugged into Bridge
Create/Get/Delete/Update functions first implementation
Few todos and gaps inside still...

Implement tunnel RPCs

---

docker-compose.yml

ci: create vxlan via grpc, remove ip link config

---

pkg/evpn/interface_test.go
pkg/evpn/svi_subnet_test.go
pkg/evpn/tunnel_vxlan_test.go
pkg/evpn/vrf_vpc_test.go

See https://github.com/opiproject/opi-spdk-bridge/issues/501

tests: Uniformly check returned error on OK response

---

pkg/evpn/evpn.go
pkg/evpn/evpn_test.go
pkg/evpn/interface.go
pkg/evpn/interface_test.go
pkg/evpn/svi_subnet.go
pkg/evpn/svi_subnet_test.go
pkg/evpn/tunnel_vxlan.go
pkg/evpn/tunnel_vxlan_test.go
pkg/evpn/vrf_vpc.go
pkg/evpn/vrf_vpc_test.go

refactoring: use resourceIDToVolumeName everywhere

---

docker-compose.yml

based on previous work https://github.com/opiproject/opi-evpn-bridge/commit/ecc50c502ead04e1aa44682dab1c0013ef8123c4

ci: create vlan bridge port via grpc, remove ip link config

---

docker-compose.yml

this will allow us to connect to FRR remotely
Until #6 is resoled

ci: enable FRR telnet

---

pkg/evpn/bridge_test.go

test(bridge): added test for illegal vlanid

---

pkg/evpn/port.go
pkg/evpn/port_test.go

fix(port): raise new error

---

pkg/evpn/vrf.go

fix(vrf): create bridge and vxlan only if VNI value is not empty

---

docker-compose.yml

ci: cleanup leftovers from old config

---

pkg/evpn/bridge.go
pkg/evpn/svi.go
pkg/evpn/vrf.go

chore: add few logs

---

pkg/evpn/evpn.go
pkg/evpn/vrf.go
pkg/utils/netlink.go

test: create NetlinkWrapper for mockery

---

pkg/evpn/bridge.go
pkg/evpn/bridge_test.go
pkg/evpn/port.go
pkg/evpn/port_test.go
pkg/evpn/svi.go
pkg/evpn/svi_test.go
pkg/evpn/vrf_test.go

- test(vrf): failed linkadd call
- test: use mockery wrapper in code
- test(svi): failed linkbyname call
- test(bridge): failed linkbyname call
- test(port): failed linkbyname call

Add more tests using mockery

---

pkg/evpn/bridge.go
pkg/evpn/bridge_test.go
pkg/evpn/vrf_test.go

test: add more mockup test for vrf and bridge

---

pkg/evpn/bridge_test.go

test(bridge): add more mockup tests

---

pkg/evpn/vrf_test.go

test(vrf): add more mockup tests

---

pkg/evpn/svi.go
pkg/evpn/svi_test.go

feat(svi): decouple linux devname from object resource id

---

pkg/evpn/bridge.go
pkg/evpn/bridge_test.go

feat(bridge): decouple linux devname from object resource id

---

pkg/evpn/svi.go
pkg/evpn/svi_test.go

test(svi): add more mockup tests

---

pkg/evpn/bridge.go
pkg/evpn/svi.go

feat: decouple linux devname from object resource id in get and update

---

pkg/evpn/bridge_test.go
pkg/evpn/port_test.go
pkg/evpn/svi_test.go
pkg/evpn/vrf_test.go

test: explicit call test params

---

pkg/evpn/bridge_test.go

test(bridge): add more mock tests

---

pkg/evpn/bridge_test.go

test(bridge): add more mock delete tests

---

pkg/evpn/bridge_test.go
pkg/evpn/port_test.go
pkg/evpn/svi_test.go
pkg/evpn/vrf_test.go

test(vrf): add more mock tests

---

pkg/evpn/bridge_test.go
pkg/evpn/port_test.go

test(port): add more mock delete tests

---

pkg/evpn/svi_test.go

test(svi): add few more mock tests

---

README.md
docker-compose.yml
pkg/evpn/bridge.go
pkg/evpn/bridge_test.go
pkg/evpn/evpn_test.go
pkg/evpn/port.go
pkg/evpn/port_test.go
pkg/evpn/svi.go
pkg/evpn/svi_test.go
pkg/evpn/vrf.go
pkg/evpn/vrf_test.go

feat: add initial impl for List funcs

---

README.md

docs: rename evpn-gw to evpn_gw in examples

---

pkg/evpn/bridge.go
pkg/evpn/bridge_test.go
pkg/evpn/evpn.go
pkg/evpn/port.go
pkg/evpn/port_test.go
pkg/evpn/svi.go
pkg/evpn/svi_test.go
pkg/evpn/vrf.go
pkg/evpn/vrf_test.go

feat(list): add more pagination limits to list funcs

---

cmd/main.go
pkg/utils/tls.go
pkg/utils/tls_test.go

feat: add TLS option for gRPC connection

---

pkg/evpn/bridge.go
pkg/evpn/bridge_validate.go
pkg/evpn/port.go
pkg/evpn/port_validate.go
pkg/evpn/svi.go
pkg/evpn/svi_validate.go
pkg/evpn/vrf.go
pkg/evpn/vrf_validate.go

refactor: move more checks to validate files

---

pkg/utils/netlink.go

feat(trace): add link name to nested netlink trace

---

pkg/utils/telnet.go

feat(trace): add nested traces for FRR commands

---

pkg/evpn/svi.go
pkg/evpn/vrf.go
pkg/utils/telnet.go

- feat(frr): enable privileged mode
- fix(frr): change telnet port
- fix(frr): support multi-line commands
- feat(frr): send example configuration commands from VRF

FRR send configuration from VRF

---

pkg/evpn/svi.go
pkg/evpn/vrf.go
pkg/utils/telnet.go

feat(frr): support multiple ports for multiple services

---

pkg/utils/telnet.go

feat(otel): add more frr attributes

---

docker-compose.yml

so we can send grpc and http commands from remote

ci: expose grpc and http ports to host

---

conf/leaf1.conf
pkg/evpn/vrf.go
pkg/evpn/vrf_frr.go

feat(frr): replace static config with dynamic grpc

---

pkg/evpn/svi.go
pkg/evpn/svi_frr.go
pkg/evpn/svi_test.go

feat(svi): prepare for FRR config in create and delete

---

pkg/utils/frr.go
pkg/utils/mocks/Frr.go

feat(frr): implement ExitPrivileged mode

---

pkg/evpn/svi_frr.go
pkg/evpn/vrf_frr.go

feat(svi): implement frr command

---

pkg/utils/frr.go

refactor(frr): split MultiLineCmd to a new function

---

pkg/evpn/svi.go
pkg/evpn/svi_netlink.go

refactor(svi): move netlink to a separate file

---

pkg/evpn/bridge.go
pkg/evpn/bridge_netlink.go

refactor(bridge): move netlink to a separate file

---

pkg/evpn/evpn.go
pkg/evpn/evpn_test.go

refactor: fix typo pe vs pb

---

pkg/models/bridge.go
pkg/models/interface.go
pkg/models/port.go
pkg/models/svi.go
pkg/models/vrf.go

fead(models): add EvpnObject interface

---

pkg/bridge/common.go
pkg/bridge/grpc.go
pkg/port/common.go
pkg/port/grpc.go
pkg/svi/common.go
pkg/svi/grpc.go
pkg/vrf/common.go
pkg/vrf/grpc.go

refactor: rename files for clarity

---

pkg/bridge/bridge_test.go
pkg/bridge/common.go
pkg/bridge/grpc.go
pkg/port/common.go
pkg/port/grpc.go
pkg/port/port_test.go
pkg/svi/common.go
pkg/svi/grpc.go
pkg/svi/svi_test.go
pkg/vrf/common.go
pkg/vrf/grpc.go
pkg/vrf/vrf_test.go

refactor: make resourceIDToFullName private and remove unused

---

pkg/bridge/common.go
pkg/bridge/grpc.go
pkg/port/common.go
pkg/port/grpc.go
pkg/svi/common.go
pkg/svi/grpc.go
pkg/utils/pagination.go
pkg/vrf/common.go
pkg/vrf/grpc.go

refactor: move pagination funs to utils

---

pkg/models/bridge.go
pkg/models/interface.go
pkg/models/port.go
pkg/models/svi.go
pkg/models/vrf.go

feat(models): add name field and getname method

---

pkg/bridge/bridge_test.go
pkg/bridge/common.go
pkg/port/common.go
pkg/port/port_test.go
pkg/svi/common.go
pkg/svi/svi_test.go
pkg/vrf/common.go
pkg/vrf/vrf_test.go

refactoring: code dup reduction in tests

---

pkg/models/bridge.go
pkg/models/port.go
pkg/models/svi.go
pkg/models/vrf.go

feat(models): add `created_at` and `updated_at` timestamps

---

cmd/main.go
pkg/utils/frr.go

feat(frr): get frr address from external config

---

pkg/utils/netlink.go

Additional netlink wrapper functions which are needed for [evpn-gw-cni](https://github.com/opiproject/opi-gateway-evpn-cni/pull/14) in order to import the netlink wrapper library

add extra netlink funcs
