- docker-compose.yml
works outside Azure:
```
Attaching to opi-evpn-bridge-opi-test-1
opi-evpn-bridge-opi-test-1  | + sleep 60
opi-evpn-bridge-opi-test-1  | + ping -c 3 5.5.5.5 -I br100
opi-evpn-bridge-opi-test-1  | PING 5.5.5.5 (5.5.5.5): 56 data bytes
opi-evpn-bridge-opi-test-1  | 64 bytes from 5.5.5.5: seq=0 ttl=64 time=0.408 ms
opi-evpn-bridge-opi-test-1  | 64 bytes from 5.5.5.5: seq=1 ttl=64 time=0.212 ms
opi-evpn-bridge-opi-test-1  | 64 bytes from 5.5.5.5: seq=2 ttl=64 time=0.181 ms
opi-evpn-bridge-opi-test-1  |
opi-evpn-bridge-opi-test-1  | --- 5.5.5.5 ping statistics ---
opi-evpn-bridge-opi-test-1  | 3 packets transmitted, 3 packets received, 0% packet loss
opi-evpn-bridge-opi-test-1  | round-trip min/avg/max = 0.181/0.267/0.408 ms …
```
> enable L3VXLAN

- README.md
- docker-compose.yml
NET_ADMIN capability is needed to avoid permission errors while executing read-write netlink commands. Adding this in opi-evpn-bridge since it shares the same network as leaf1.
> Added NET_ADMIN capability to evpn bridge container

- pkg/evpn/evpn.go
that is separate the input from the assigned and the return object.
Fix issue https://github.com/opiproject/opi-spdk-bridge/issues/438
> align proto clone to the same pattern

- README.md
- cmd/main.go
- pkg/evpn/evpn.go
- initialize the structures
- use full name instead of {resource}_id
> use full name instead of {resource}_id

- pkg/evpn/interface_test.go
- pkg/evpn/svi_subnet_test.go
- pkg/evpn/tunnel_vxlan_test.go
- pkg/evpn/vrf_test.go
instead of marshal or deepequal
code reduction
> tests: use proto.Equal

- pkg/evpn/bridge.go
- pkg/evpn/bridge_test.go
> fix(bridge): create vxlan only if VNI is not empty

- conf/bleaf.conf
- conf/leaf1.conf
- docker-compose.yml
This pull request has been created from the PR https://github.com/opiproject/opi-evpn-bridge/pull/76
> Moving the overlay networks to vlan aware bridge in leaf1

- pkg/evpn/vrf.go
> chore: add few logs

- pkg/evpn/bridge.go
> fix(bridge): delete and get only if VNI is not empty

- pkg/evpn/vrf.go
> feat(vrf): delete bridge and vxlan netdevs

- pkg/evpn/bridge_test.go
- pkg/evpn/port_test.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_test.go
- test: init using NewNetlink function
- test: start using mockery
- fix(vrf): handle empty Vni case
- see #130
> ci: start using mockery

- Makefile
> ci: add makefile for development

- pkg/evpn/bridge_test.go
- pkg/evpn/port_test.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf_test.go
This is done by creating object copy.
This reduces test dependencies.
> test: prevent global test objects modification

- pkg/evpn/bridge_test.go
- pkg/evpn/port_test.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf_test.go
Fixing leftover TODO to refactory EXPECT
instead of switch case, move expect statements
from mockery inside each individual test
> test: move mocks into table driver unittests

- pkg/evpn/bridge.go
- pkg/evpn/bridge_test.go
- pkg/evpn/evpn.go
- pkg/evpn/port.go
- pkg/evpn/port_test.go
- pkg/evpn/svi.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_test.go
> feat(list): add pagination to list funcs

- Dockerfile
- README.md
- cmd/main.go
- docker-compose.yml
- go.mod
- go.sum
this is using inventory service as an example
once we fix opi-api compiler we can remove inventory
and replace it with network gw registration
> feat: add grpc gw http listener

- pkg/evpn/bridge.go
- pkg/evpn/bridge_validate.go
- pkg/evpn/port.go
- pkg/evpn/port_validate.go
- pkg/evpn/svi.go
- pkg/evpn/svi_validate.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_validate.go
> refactor: split validate logic to a new file

- pkg/evpn/bridge.go
- pkg/evpn/bridge_validate.go
- pkg/evpn/port.go
- pkg/evpn/port_validate.go
- pkg/evpn/svi.go
- pkg/evpn/svi_validate.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_validate.go
> refactor(update): move mask check to validate files

- go.mod
- go.sum
- pkg/evpn/bridge.go
- pkg/evpn/port.go
- pkg/evpn/svi.go
- pkg/evpn/vrf.go
- pkg/utils/telnet.go
I'm using telnet until #6 is resolved
> feat(frr): call frr cmds via telnet

- pkg/evpn/bridge_test.go
- pkg/evpn/evpn.go
- pkg/evpn/evpn_test.go
- pkg/evpn/port_test.go
- pkg/evpn/svi.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_test.go
- pkg/utils/frr.go
> test(frr): start using mockery

- pkg/evpn/svi.go
- pkg/evpn/svi_netlink.go
> refactor(svi): move netlink to a separate file

- pkg/evpn/vrf.go
- pkg/evpn/vrf_netlink.go
> refactor(vrf): move netlink to a separate file

- cmd/main.go
- go.mod
- go.sum
- pkg/evpn/bridge_test.go
- pkg/evpn/evpn.go
- pkg/evpn/evpn_test.go
- pkg/evpn/port_test.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf_test.go
> feat(store): use gokv pkg to abstract persistant store

- pkg/evpn/bridge.go
- pkg/evpn/port.go
- pkg/evpn/svi.go
- pkg/evpn/vrf.go
- pkg/models/bridge.go
- pkg/models/port.go
- pkg/models/svi.go
- pkg/models/vrf.go
This is just a first draft and will be amended later on to include more fields and fix Todos...
There are 4 objects:
- [`LogicalBridgeSpec`](https://github.com/opiproject/opi-api/blob/d81cc5ee60d4df53cf660ced62e8fe5b17de4cfd/network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto#L132-L144)
- [`BridgePortSpec`](https://github.com/opiproject/opi-api/blob/d81cc5ee60d4df53cf660ced62e8fe5b17de4cfd/network/evpn-gw/v1alpha1/l2_xpu_infra_mgr.proto#L238-L246)
- [`SviSpec`](https://github.com/opiproject/opi-api/blob/d81cc5ee60d4df53cf660ced62e8fe5b17de4cfd/network/evpn-gw/v1alpha1/l3_xpu_infra_mgr.proto#L256-L279)
- [`VrfSpec`](https://github.com/opiproject/opi-api/blob/d81cc5ee60d4df53cf660ced62e8fe5b17de4cfd/network/evpn-gw/v1alpha1/l3_xpu_infra_mgr. …
> feat(models): add new package to handle protobuf translation

- cmd/main.go
- pkg/evpn/bridge.go
- pkg/evpn/bridge_test.go
- pkg/evpn/evpn.go
- pkg/evpn/port.go
- pkg/evpn/port_test.go
- pkg/evpn/svi.go
- pkg/evpn/svi_test.go
- pkg/evpn/vrf.go
- pkg/evpn/vrf_test.go
- pkg/utils/codec.go
see https://github.com/philippgille/gokv
> feat(store): replace all 4 objects maps with gokv.Store abstraction

- pkg/bridge/bridge_test.go
- pkg/bridge/common.go
- pkg/bridge/grpc.go
- pkg/port/common.go
- pkg/port/grpc.go
- pkg/port/port_test.go
- pkg/svi/common.go
- pkg/svi/grpc.go
- pkg/svi/svi_test.go
- pkg/utils/proto.go
- pkg/vrf/common.go
- pkg/vrf/grpc.go
- pkg/vrf/vrf_test.go
> refactor: move proto to utils

- pkg/utils/frr.go
- pkg/utils/netlink.go
Make tracer optional so we can import the netlinkWrapper library from evpn-gw-cni. 
More info here: https://github.com/opiproject/opi-gateway-evpn-cni/pull/14#discussion_r1515365216
> fix(evpn-bridge): make tracer optional

- docker-compose.yml
Due to an incorrect subnet in docker compose file the CI was failing
> fix(evpn-bridge): fix incorrect subnet in CI

- pkg/frr/frr.go
- pkg/infradb/bridge.go
- pkg/infradb/common/common.go
- pkg/infradb/infradb.go
- pkg/infradb/port.go
- pkg/infradb/replay.go
- pkg/infradb/subscriberframework/actionbus/actionbus.go
- pkg/infradb/subscriberframework/eventbus/eventbus.go
- pkg/infradb/svi.go
- pkg/infradb/taskmanager/taskmanager.go
- pkg/infradb/utils.go
- pkg/infradb/vrf.go
- pkg/utils/helpers.go
- pkg/utils/netlink.go
In order to move the evpn-gw-bridge into a more resilient path we have implemented the replaydb feature.
When a module (e.g. FRR module) confronts a permanent error then stops retrying and the replay procedure kicks in. The replay procedure will clean up all the system configuration (e.g. FRR daemon) that is related to the failed module and will replay the relevant objects from the database in order to bring the system configuration back on track again.
The replay feature currently is only supported for the FRR module and the FRR daemon. Support for all the modules will be added in the future
> Introduce replaydb feature

- pkg/LinuxCIModule/lci.go
- pkg/LinuxGeneralModule/lgm.go
- pkg/frr/frr.go
- pkg/utils/frr.go
fix: frr handle the duplicate vni and deleting of non-existence vrf and svi.
> fix(evpn-bridge): fix for frr to handle vrf setup and teardown

- pkg/LinuxGeneralModule/lgm.go
- pkg/utils/idpool.go
idpool feature for generating id's for mod pointer, routing table id , trie pointer.
> feat(idpool): idpool feature for generating id's
